language: generic
services:
  - docker

before_install:
  - docker build -t mikemaberry/nginx-auto-ssl -f Dockerfile .

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "resty-auto-ssl"
  env: "RestyAutoSsl-env"
  bucket_name: "elasticbeanstalk-us-east-2-886075860709"
  bucket_path: "resty-auto-ssl"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"